#!/bin/bash

VERSION=1.0

if [ $# -lt 1 ]; then
    >&2 echo "You need to provide command to mock!"
    exit 1
fi

command=$1
shift
args=( "$@" )
command_file=$(basename "${command}")

if ! type "${command}" > /dev/null 2>&1 ; then
    >&2 echo "I cannot run ${command} ;("
    exit 2
fi

if [ ! -d "mocks" ]; then
    mkdir mocks
fi

funame=p_$(echo -n "${args[@]}" | md5sum | cut -d" " -f1)

# Create ending part of file with function call
if [ ! -e "mocks/${command_file}" ]; then
    cat << EOF > mocks/${command_file}
#!/bin/bash

#### CONFIG SECTION ####

# shellcheck disable=SC2034
MOCKMAKER_VERSION=${VERSION}

#### END OF CONFIG SECTION ####

# For command: ${command_file}
funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
if ! type "\${funame}" > /dev/null 2>&1; then
    >&2 echo "ERROR: \$0 \$* is not mocked"
    exit 1
fi
\$funame
EOF
else
    grep "${funame}" "mocks/${command_file}" > /dev/null 2>&1
    if [ $? -ne 1 ]; then
        >&2 echo "${command} ${args[*]} is mocked already"
        exit 3
    fi
fi

stdout=$(${command} "${args[@]}" 2> "mocks/stderr_${funame}_tmp")
exitcode=$?
stdout=${stdout//\\/\\\\}
stdout=${stdout//\"/\\\"}
stdout=${stdout//\$/\\\$}
stderr=$(cat "mocks/stderr_${funame}_tmp")
rm "mocks/stderr_${funame}_tmp"

echo "stdout: $stdout"
echo "stderr: $stderr"
echo "exit code: $exitcode"

mv "mocks/${command_file}" "mocks/${command_file}_old"

echos=""
if [ -n "${stdout}" ]; then
    echos+="
    echo \"${stdout}\""
fi
if [ -n "${stderr}" ]; then
    echos+="
    >&2 echo \"${stderr}\""
fi

# Create new function for current args
cat << EOF > mocks/${command_file}_func

# For param: ${args[@]}
function ${funame} {${echos}
    exit ${exitcode}
}
EOF

# put head (from start to end of config), new function and rest of script together
config_end=$(grep -n -m 1 "#### END OF CONFIG SECTION ####" "mocks/${command_file}_old" | cut -d":" -f1)
head -n $config_end "mocks/${command_file}_old" > "mocks/${command_file}"
cat "mocks/${command_file}_func" >> "mocks/${command_file}"
let config_end+=1
tail -n+${config_end} "mocks/${command_file}_old" >> "mocks/${command_file}"
rm "mocks/${command_file}_old" "mocks/${command_file}_func"

chmod +x "mocks/${command_file}"
