#!/bin/bash

VERSION=1.0

MOCKS_DIR="mocks"

if [ $# -lt 1 ]; then
    >&2 echo "You need to provide command to mock!"
    exit 1
fi

command=$1
shift
args=( "$@" )
command_file=$(basename "${command}")

if ! type "${command}" > /dev/null 2>&1 ; then
    >&2 echo "I cannot run ${command} ;("
    exit 2
fi

if [ ! -d "${MOCKS_DIR}" ]; then
    mkdir ${MOCKS_DIR}
fi

funame=p_$(echo -n "${args[@]}" | md5sum | cut -d" " -f1)

# Create ending part of file with function call
if [ ! -e "${MOCKS_DIR}/${command_file}" ]; then
    cat << EOF > ${MOCKS_DIR}/${command_file}
#!/bin/bash

#### CONFIG SECTION ####

# shellcheck disable=SC2034
MOCKMAKER_VERSION=${VERSION}

#### END OF CONFIG SECTION ####

# For command: ${command_file}
funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
if ! type "\${funame}" > /dev/null 2>&1; then
    >&2 echo "ERROR: \$0 \$* is not mocked"
    exit 1
fi
\$funame
EOF
else
    grep "${funame}" "${MOCKS_DIR}/${command_file}" > /dev/null 2>&1
    if [ $? -ne 1 ]; then
        >&2 echo "${command} ${args[*]} is mocked already"
        exit 3
    fi
fi

function cleanup () {
    cleaned=$1
    cleaned=${cleaned//\\/\\\\}
    cleaned=${cleaned//\"/\\\"}
    cleaned=${cleaned//\$/\\\$}
    echo "${cleaned}"
}

stdout=$(${command} "${args[@]}" 2> "/tmp/mockmaker_stderr_${funame}_tmp")
exitcode=$?
stdout=$(cleanup "$stdout")
stderr=$(cat "/tmp/mockmaker_stderr_${funame}_tmp")
stderr=$(cleanup "$stderr")
rm "/tmp/mockmaker_stderr_${funame}_tmp"

echo "stdout: $stdout"
echo "stderr: $stderr"
echo "exit code: $exitcode"

mv "${MOCKS_DIR}/${command_file}" "/tmp/mockmaker_${command_file}_old"

echos=""
if [ -n "${stdout}" ]; then
    echos+="
    echo \"${stdout}\""
fi
if [ -n "${stderr}" ]; then
    echos+="
    >&2 echo \"${stderr}\""
fi

# Create new function for current args
cat << EOF > /tmp/mockmaker_${command_file}_func

# For param: ${args[@]}
function ${funame} {${echos}
    exit ${exitcode}
}
EOF

# put head (from start to end of config), new function and rest of script together
config_end=$(grep -n -m 1 "#### END OF CONFIG SECTION ####" "/tmp/mockmaker_${command_file}_old" | cut -d":" -f1)
head -n $config_end "/tmp/mockmaker_${command_file}_old" > "${MOCKS_DIR}/${command_file}"
cat "/tmp/mockmaker_${command_file}_func" >> "${MOCKS_DIR}/${command_file}"
let config_end+=1
tail -n+${config_end} "/tmp/mockmaker_${command_file}_old" >> "${MOCKS_DIR}/${command_file}"
rm "/tmp/mockmaker_${command_file}_old" "/tmp/mockmaker_${command_file}_func"

chmod +x "${MOCKS_DIR}/${command_file}"
