#!/bin/bash

VERSION=1.0

if [ $# -lt 1 ]; then
    >&2 echo "You need to provide command to mock!"
    exit 1
fi

command=$1
shift
args=( "$@" )
command_file=$(basename "${command}")

if ! type "${command}" > /dev/null 2>&1 ; then
    >&2 echo "I cannot run ${command} ;("
    exit 2
fi

if [ ! -d "mocks" ]; then
    mkdir mocks
fi

funame=p_$(echo -n "${args[@]}" | md5sum | cut -d" " -f1)

# Create ending part of file with function call
if [ ! -e "mocks/${command_file}" ]; then
    cat << EOF > mocks/${command_file}


# shellcheck disable=SC2034
MOCKMAKER_VERSION=${VERSION}

# For command: ${command_file}
funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
if ! type "\${funame}" > /dev/null 2>&1; then
    >&2 echo "ERROR: \$0 \$* is not mocked"
    exit 1
fi
\$funame
EOF
else
    grep "${funame}" "mocks/${command_file}" > /dev/null 2>&1
    if [ $? -ne 1 ]; then
        >&2 echo "${command} ${args[*]} is mocked already"
        exit 3
    fi
fi

function cleanup () {
    cleaned=$1
    cleaned=${cleaned//\\/\\\\}
    cleaned=${cleaned//\"/\\\"}
    cleaned=${cleaned//\$/\\\$}
    echo "${cleaned}"
}

stdout=$(${command} "${args[@]}" 2> "mocks/stderr_${funame}_tmp")
exitcode=$?
stdout=$(cleanup "$stdout")
stderr=$(cat "mocks/stderr_${funame}_tmp")
stderr=$(cleanup "$stderr")
rm "mocks/stderr_${funame}_tmp"

echo "stdout: $stdout"
echo "stderr: $stderr"
echo "exit code: $exitcode"

mv "mocks/${command_file}" "mocks/${command_file}_tmp"

echos=""
if [ -n "${stdout}" ]; then
    echos+="
    echo \"${stdout}\""
fi
if [ -n "${stderr}" ]; then
    echos+="
    >&2 echo \"${stderr}\""
fi

# Create new function for current args
cat << EOF > mocks/${command_file}
#!/bin/bash

# For param: ${args[@]}
function ${funame} {${echos}
    exit ${exitcode}
}
EOF

# Add old file below new function (but ommit first line, as that should be shebang)
tail --lines=+2 "mocks/${command_file}_tmp" >> "mocks/${command_file}"
rm "mocks/${command_file}_tmp"

chmod +x "mocks/${command_file}"
