#!/bin/bash

command=$1
shift
args=$@

if [ ! -d "mocks" ]; then
    mkdir mocks
fi

stdout=$(${command} ${args} 2> mocks/stderr_tmp)
exitcode=$?
stderr=$(cat mocks/stderr_tmp)
rm mocks/stderr_tmp

echo "stdout: $stdout"
echo "stderr: $stderr"
echo "exit code: $exitcode"

funame=p_$(echo -n "${args}" | md5sum | cut -d" " -f1)

if [ ! -e mocks/${command} ]; then
    cat << EOF > mocks/${command}


funame=p_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
\$funame
EOF
fi

mv mocks/${command} mocks/${command}_tmp

cat << EOF > mocks/${command}
#!/bin/bash

# For param: ${args}
function ${funame} {
    echo "${stdout}"
    >&2 echo "${stderr}"
    exit ${exitcode}
}
EOF

tail --lines=+2 mocks/${command}_tmp >> mocks/${command}
rm mocks/${command}_tmp

chmod +x mocks/${command}
