#!/bin/bash

command=$1
shift
args=$@

echo "command: $command"
echo "args: $args"

if [ ! -d "mocks" ]; then
    mkdir mocks
fi

stdout=$(${command} ${args})
exitcode=$?

echo $stdout
echo "exit code: $exitcode"

funame=f_$(echo -n "${args}" | md5sum | cut -d" " -f1)
cat << EOF >> mocks/${command}
function ${funame} {
    echo "${stdout}"
    exit ${exitcode}
}

funame=f_\$(echo -n "\$@" | md5sum | cut -d" " -f1)
\$funame
EOF

chmod +x mocks/${command}
